In [1]:
#import library
import pandas as pd

In [2]:
#load dataset
data=pd.read_csv("car prediction data.csv")

In [3]:
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
data.tail()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
296,city,2016,9.50,11.6,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.9,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,0

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    str
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    str
 6   Seller_Type    301 non-null    str
 7   Transmission   301 non-null    str
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), str(4)
memory usage: 21.3 KB

In [6]:
data.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [7]:
data.shape

(301, 9)

In [8]:
data.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='str')

In [9]:
#missing values
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [10]:
#count duplicates
data.duplicated().sum()

np.int64(2)

In [12]:
#remove duplicates
data.drop_duplicates()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [14]:
#filtering data
data[data['Selling_Price']>7.25]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0
12,ciaz,2015,7.50,9.94,15000,Petrol,Dealer,Automatic,0
15,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0
17,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0
29,ciaz,2015,7.45,10.38,45000,Diesel,Dealer,Manual,0
45,ciaz,2014,7.50,12.04,15000,Petrol,Dealer,Automatic,0
49,ciaz,2017,7.75,9.29,37000,Petrol,Dealer,Automatic,0
50,fortuner,2012,14.90,30.61,104707,Diesel,Dealer,Automatic,0
51,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
52,innova,2017,18.00,19.77,15000,Diesel,Dealer,Automatic,0
53,fortuner,2013,16.00,30.61,135000,Diesel,Individual,Automatic,0
59,fortuner,2014,19.99,35.96,41000,Diesel,Dealer,Automatic,0
62,fortuner,2014,18.75,35.96,78000,Diesel,Dealer,Automatic,0
63,fortuner,2015,23.50,35.96,47000,Diesel,Dealer,Automatic,0
64,fortuner,2017,33.00,36.23,6000,Diesel,Dealer,Automatic,0
66,innova,2017,19.75,23.15,11000,Petrol,Dealer,Automatic,0
67,fortuner,2010,9.25,20.45,59000,Diesel,Dealer,Manual,0
69,corolla altis,2016,14.25,20.91,12000,Petrol,Dealer,Manual,0
72,corolla altis,2013,7.45,18.61,56001,Petrol,Dealer,Manual,0
79,fortuner,2012,14.50,30.61,89000,Diesel,Dealer,Automatic,0
80,corolla altis,2016,14.73,14.89,23000,Diesel,Dealer,Manual,0
82,innova,2017,23.00,25.39,15000,Diesel,Dealer,Automatic,0
83,innova,2015,12.50,13.46,38000,Diesel,Dealer,Manual,0
86,land cruiser,2010,35.00,92.60,78000,Diesel,Dealer,Manual,0
91,innova,2014,11.25,16.09,58242,Diesel,Dealer,Manual,0
93,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
96,innova,2016,20.75,25.39,29000,Diesel,Dealer,Automatic,0
97,corolla altis,2017,17.00,18.64,8700,Petrol,Dealer,Manual,0
99,fortuner,2010,9.65,20.45,50024,Diesel,Dealer,Manual,0
208,i20,2017,7.90,8.10,3435,Petrol,Dealer,Manual,0
211,elantra,2015,11.75,14.79,43535,Diesel,Dealer,Manual,0
212,creta,2016,11.25,13.60,22671,Petrol,Dealer,Manual,0
223,verna,2015,8.25,9.40,61381,Diesel,Dealer,Manual,0
231,verna,2017,9.25,9.40,15001,Petrol,Dealer,Manual,0
232,elantra,2015,11.45,14.79,12900,Petrol,Dealer,Automatic,0
235,verna,2017,9.10,9.40,15141,Petrol,Dealer,Manual,0
237,creta,2015,11.25,13.60,68000,Diesel,Dealer,Manual,0
250,creta,2016,12.90,13.60,35934,Diesel,Dealer,Manual,0
256,city,2016,10.25,13.60,49562,Petrol,Dealer,Manual,0
257,city,2015,8.50,13.60,40324,Petrol,Dealer,Manual,0
258,city,2015,8.40,13.60,25000,Petrol,Dealer,Manual,0
260,city,2016,9.15,13.60,29223,Petrol,Dealer,Manual,0
267,city,2016,8.35,9.40,19434,Diesel,Dealer,Manual,0
272,city,2015,7.50,10.00,27600,Petrol,Dealer,Manual,0
275,city,2016,10.90,13.60,30753,Petrol,Dealer,Automatic,0
276,city,2015,8.65,13.60,24800,Petrol,Dealer,Manual,0
277,city,2015,9.70,13.60,21780,Petrol,Dealer,Manual,0
282,city,2014,8.25,14.00,63000,Diesel,Dealer,Manual,0
283,city,2016,8.99,11.80,9010,Petrol,Dealer,Manual,0
285,jazz,2016,7.40,8.50,15059,Petrol,Dealer,Automatic,0
288,city,2015,8.40,13.60,34000,Petrol,Dealer,Manual,0
289,city,2016,10.11,13.60,10980,Petrol,Dealer,Manual,0
295,city,2015,8.55,13.09,60076,Diesel,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0

In [15]:
data[data['Owner']>=1]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
58,etios g,2014,4.10,6.80,39485,Petrol,Dealer,Manual,1
85,camry,2006,2.50,23.73,142000,Petrol,Individual,Automatic,3
106,Hyosung GT250R,2014,1.35,3.45,16500,Petrol,Individual,Manual,1
184,Bajaj Pulsar 150,2008,0.25,0.75,26000,Petrol,Individual,Manual,1
191,Bajaj Discover 125,2012,0.20,0.57,25000,Petrol,Individual,Manual,1
192,Hero Hunk,2007,0.20,0.75,49000,Petrol,Individual,Manual,1
193,Hero Ignitor Disc,2013,0.20,0.65,24000,Petrol,Individual,Manual,1
198,Bajaj Discover 125,2011,0.15,0.57,35000,Petrol,Individual,Manual,1
201,i20,2010,3.25,6.79,58000,Diesel,Dealer,Manual,1
205,grand i10,2016,5.25,5.70,3493,Petrol,Dealer,Manual,1
241,xcent,2015,4.75,7.13,35866,Petrol,Dealer,Manual,1

In [17]:
data[(data['Year']>2013)&(data['Fuel_Type']=='Diesel')]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0
11,ciaz,2015,6.85,10.38,51000,Diesel,Dealer,Manual,0
15,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0
16,ertiga,2015,7.25,10.79,41678,Diesel,Dealer,Manual,0
17,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0
29,ciaz,2015,7.45,10.38,45000,Diesel,Dealer,Manual,0
32,swift,2014,4.95,7.49,39000,Diesel,Dealer,Manual,0
33,ertiga,2014,6.00,9.95,45000,Diesel,Dealer,Manual,0
34,dzire,2014,5.50,8.06,45000,Diesel,Dealer,Manual,0
43,dzire,2014,5.50,8.06,45780,Diesel,Dealer,Manual,0
51,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
52,innova,2017,18.00,19.77,15000,Diesel,Dealer,Automatic,0
59,fortuner,2014,19.99,35.96,41000,Diesel,Dealer,Automatic,0
62,fortuner,2014,18.75,35.96,78000,Diesel,Dealer,Automatic,0
63,fortuner,2015,23.50,35.96,47000,Diesel,Dealer,Automatic,0
64,fortuner,2017,33.00,36.23,6000,Diesel,Dealer,Automatic,0
65,etios liva,2014,4.75,6.95,45000,Diesel,Dealer,Manual,0
70,etios liva,2014,3.95,6.76,71000,Diesel,Dealer,Manual,0
74,etios cross,2014,4.90,8.93,83000,Diesel,Dealer,Manual,0
80,corolla altis,2016,14.73,14.89,23000,Diesel,Dealer,Manual,0
81,etios gd,2015,4.75,7.85,40000,Diesel,Dealer,Manual,0
82,innova,2017,23.00,25.39,15000,Diesel,Dealer,Automatic,0
83,innova,2015,12.50,13.46,38000,Diesel,Dealer,Manual,0
91,innova,2014,11.25,16.09,58242,Diesel,Dealer,Manual,0
93,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
96,innova,2016,20.75,25.39,29000,Diesel,Dealer,Automatic,0
209,grand i10,2015,4.85,5.70,21125,Diesel,Dealer,Manual,0
211,elantra,2015,11.75,14.79,43535,Diesel,Dealer,Manual,0
222,i20,2014,6.00,7.60,77632,Diesel,Dealer,Manual,0
223,verna,2015,8.25,9.40,61381,Diesel,Dealer,Manual,0
237,creta,2015,11.25,13.60,68000,Diesel,Dealer,Manual,0
250,creta,2016,12.90,13.60,35934,Diesel,Dealer,Manual,0
253,city,2014,7.20,9.90,48000,Diesel,Dealer,Manual,0
267,city,2016,8.35,9.40,19434,Diesel,Dealer,Manual,0
282,city,2014,8.25,14.00,63000,Diesel,Dealer,Manual,0
295,city,2015,8.55,13.09,60076,Diesel,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0

In [18]:
data[(data['Car_Name']=='city')&(data['Transmission']=='Manual')]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
251,city,2013,5.00,9.90,56701,Petrol,Dealer,Manual,0
253,city,2014,7.20,9.90,48000,Diesel,Dealer,Manual,0
254,city,2013,5.25,9.90,54242,Petrol,Dealer,Manual,0
256,city,2016,10.25,13.60,49562,Petrol,Dealer,Manual,0
257,city,2015,8.50,13.60,40324,Petrol,Dealer,Manual,0
258,city,2015,8.40,13.60,25000,Petrol,Dealer,Manual,0
260,city,2016,9.15,13.60,29223,Petrol,Dealer,Manual,0
267,city,2016,8.35,9.40,19434,Diesel,Dealer,Manual,0
269,city,2015,6.70,10.00,18828,Petrol,Dealer,Manual,0
270,city,2011,4.10,10.00,69341,Petrol,Dealer,Manual,0
271,city,2009,3.00,10.00,69562,Petrol,Dealer,Manual,0
272,city,2015,7.50,10.00,27600,Petrol,Dealer,Manual,0
276,city,2015,8.65,13.60,24800,Petrol,Dealer,Manual,0
277,city,2015,9.70,13.60,21780,Petrol,Dealer,Manual,0
279,city,2014,6.25,13.60,40126,Petrol,Dealer,Manual,0
281,city,2006,2.10,7.60,50456,Petrol,Dealer,Manual,0
282,city,2014,8.25,14.00,63000,Diesel,Dealer,Manual,0
283,city,2016,8.99,11.80,9010,Petrol,Dealer,Manual,0
288,city,2015,8.40,13.60,34000,Petrol,Dealer,Manual,0
289,city,2016,10.11,13.60,10980,Petrol,Dealer,Manual,0
293,city,2010,3.25,9.90,38000,Petrol,Dealer,Manual,0
295,city,2015,8.55,13.09,60076,Diesel,Dealer,Manual,0
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0

In [19]:
#sorting highest price
data.sort_values('Selling_Price',ascending=False)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
86,land cruiser,2010,35.00,92.60,78000,Diesel,Dealer,Manual,0
64,fortuner,2017,33.00,36.23,6000,Diesel,Dealer,Automatic,0
63,fortuner,2015,23.50,35.96,47000,Diesel,Dealer,Automatic,0
51,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
93,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
...,...,...,...,...,...,...,...,...,...
196,Activa 3g,2008,0.17,0.52,500000,Petrol,Individual,Automatic,0
197,Honda CB twister,2010,0.16,0.51,33000,Petrol,Individual,Manual,0
198,Bajaj Discover 125,2011,0.15,0.57,35000,Petrol,Individual,Manual,1
199,Honda CB Shine,2007,0.12,0.58,53000,Petrol,Individual,Manual,0
200,Bajaj Pulsar 150,2006,0.10,0.75,92233,Petrol,Individual,Manual,0

In [20]:
#sorting lowest price
data.sort_values('Selling_Price')

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
200,Bajaj Pulsar 150,2006,0.10,0.75,92233,Petrol,Individual,Manual,0
199,Honda CB Shine,2007,0.12,0.58,53000,Petrol,Individual,Manual,0
198,Bajaj Discover 125,2011,0.15,0.57,35000,Petrol,Individual,Manual,1
197,Honda CB twister,2010,0.16,0.51,33000,Petrol,Individual,Manual,0
196,Activa 3g,2008,0.17,0.52,500000,Petrol,Individual,Automatic,0
...,...,...,...,...,...,...,...,...,...
93,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
51,fortuner,2015,23.00,30.61,40000,Diesel,Dealer,Automatic,0
63,fortuner,2015,23.50,35.96,47000,Diesel,Dealer,Automatic,0
64,fortuner,2017,33.00,36.23,6000,Diesel,Dealer,Automatic,0
86,land cruiser,2010,35.00,92.60,78000,Diesel,Dealer,Manual,0

In [27]:
#groupby analysis
data.groupby('Car_Name')['Present_Price'].mean().sort_values(ascending=False)

Car_Name
land cruiser          92.600000
fortuner              30.732727
camry                 23.730000
innova                17.846667
corolla altis         17.582500
                        ...
Honda Activa 4G        0.510000
Honda CB twister       0.510000
Hero Splender Plus     0.480000
Bajaj Discover 100     0.470000
Bajaj  ct 100          0.320000
Name: Present_Price, Length: 98, dtype: float64

In [25]:
data.groupby('Fuel_Type')['Kms_Driven'].mean().sort_values(ascending=False)

Fuel_Type
Diesel    50369.916667
CNG       42749.000000
Petrol    33528.937238
Name: Kms_Driven, dtype: float64

In [26]:
data.groupby('Fuel_Type')['Kms_Driven'].min()

Fuel_Type
CNG       35500
Diesel     2071
Petrol      500
Name: Kms_Driven, dtype: int64

In [28]:
#value counts
data['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [29]:
data['Owner'].value_counts()

Owner
0    290
1     10
3      1
Name: count, dtype: int64

In [31]:
data['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [32]:
data['Car_Name'].value_counts()

Car_Name
city                   26
corolla altis          16
verna                  14
fortuner               11
brio                   10
                       ..
Hero Super Splendor     1
Hero Hunk               1
Hero  Ignitor Disc      1
Hero  CBZ Xtreme        1
Bajaj  ct 100           1
Name: count, Length: 98, dtype: int64

In [33]:
#data analysis
data[['Selling_Price','Present_Price','Kms_Driven']].describe()

       Selling_Price  Present_Price     Kms_Driven
count     301.000000     301.000000     301.000000
mean        4.661296       7.628472   36947.205980
std         5.082812       8.644115   38886.883882
min         0.100000       0.320000     500.000000
25%         0.900000       1.200000   15000.000000
50%         3.600000       6.400000   32000.000000
75%         6.000000       9.900000   48767.000000
max        35.000000      92.600000  500000.000000

In [35]:
data[['Car_Name','Fuel_Type']].describe()

       Car_Name Fuel_Type
count       301       301
unique       98         3
top        city    Petrol
freq         26       239