In [1]:
#Import library
import pandas as pd

In [2]:
#load dataset
patients=pd.read_csv("patients.csv")
appointments=pd.read_csv("appointments.csv")
billing=pd.read_csv("billing.csv")
doctors=pd.read_csv("doctors.csv")
treatments=pd.read_csv("treatments.csv")

In [3]:
patients.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [5]:
patients.tail()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
45,P046,Michael,Taylor,F,1986-09-01,8019925828,456 Oak Ave,2021-07-31,MedCare Plus,INS368799,michael.taylor@mail.com
46,P047,Jane,Moore,M,1995-12-13,8715732851,321 Maple Dr,2022-05-20,WellnessCorp,INS337549,jane.moore@mail.com
47,P048,Emily,Miller,M,1983-03-24,8720989381,123 Elm St,2023-06-19,PulseSecure,INS694319,emily.miller@mail.com
48,P049,David,Moore,M,1972-11-26,7712937941,321 Maple Dr,2023-06-14,MedCare Plus,INS584299,david.moore@mail.com
49,P050,Laura,Wilson,M,1993-12-27,8301134730,321 Maple Dr,2023-04-28,WellnessCorp,INS712210,laura.wilson@mail.com

In [6]:
patients.shape

(50, 11)

In [7]:
patients.describe()

       contact_number
count    5.000000e+01
mean     7.817283e+09
std      9.573594e+08
min      6.141952e+09
25%      7.065593e+09
50%      7.749927e+09
75%      8.599947e+09
max      9.900972e+09

In [8]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     str
 1   first_name          50 non-null     str
 2   last_name           50 non-null     str
 3   gender              50 non-null     str
 4   date_of_birth       50 non-null     str
 5   contact_number      50 non-null     int64
 6   address             50 non-null     str
 7   registration_date   50 non-null     str
 8   insurance_provider  50 non-null     str
 9   insurance_number    50 non-null     str
 10  email               50 non-null     str
dtypes: int64(1), str(10)
memory usage: 4.4 KB

In [9]:
patients.columns

Index(['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth',
       'contact_number', 'address', 'registration_date', 'insurance_provider',
       'insurance_number', 'email'],
      dtype='str')

In [10]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [11]:
appointments.tail()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
195,A196,P045,D006,2023-10-26,9:45:00,Checkup,Cancelled
196,A197,P001,D005,2023-04-01,13:30:00,Emergency,No-show
197,A198,P022,D006,2023-05-15,8:30:00,Therapy,No-show
198,A199,P017,D001,2023-05-01,12:45:00,Follow-up,Completed
199,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled

In [12]:
appointments.describe()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
count,200,200,200,200,200,200,200
unique,200,48,10,158,40,5,4
top,A001,P012,D005,2023-08-16,15:30:00,Checkup,No-show
freq,1,10,29,5,9,45,52

In [13]:
appointments.shape

(200, 7)

In [14]:
appointments.columns

Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_date',
       'appointment_time', 'reason_for_visit', 'status'],
      dtype='str')

In [15]:
appointments.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    str
 1   patient_id        200 non-null    str
 2   doctor_id         200 non-null    str
 3   appointment_date  200 non-null    str
 4   appointment_time  200 non-null    str
 5   reason_for_visit  200 non-null    str
 6   status            200 non-null    str
dtypes: str(7)
memory usage: 11.1 KB

In [16]:
billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [17]:
billing.tail()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
195,B196,P045,T196,2023-10-26,2477.80,Cash,Pending
196,B197,P001,T197,2023-04-01,975.49,Cash,Pending
197,B198,P022,T198,2023-05-15,3383.72,Cash,Failed
198,B199,P017,T199,2023-05-01,1472.17,Credit Card,Paid
199,B200,P007,T200,2023-12-30,3288.15,Insurance,Paid

In [18]:
billing.describe()

            amount
count   200.000000
mean   2756.249250
std    1298.125308
min     534.030000
25%    1563.412500
50%    2828.165000
75%    3836.627500
max    4973.630000

In [19]:
billing.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    str
 1   patient_id      200 non-null    str
 2   treatment_id    200 non-null    str
 3   bill_date       200 non-null    str
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    str
 6   payment_status  200 non-null    str
dtypes: float64(1), str(6)
memory usage: 11.1 KB

In [20]:
billing.shape

(200, 7)

In [21]:
billing.columns

Index(['bill_id', 'patient_id', 'treatment_id', 'bill_date', 'amount',
       'payment_method', 'payment_status'],
      dtype='str')

In [22]:
doctors.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com

In [23]:
doctors.tail()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
5,D006,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
6,D007,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
7,D008,Linda,Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com
8,D009,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
9,D010,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

In [24]:
doctors.describe()

       phone_number  years_experience
count  1.000000e+01           10.0000
mean   7.919716e+09           21.5000
std    1.142890e+09            6.7536
min    6.176384e+09            5.0000
25%    6.792438e+09           19.5000
50%    8.269752e+09           23.5000
75%    8.937722e+09           26.0000
max    9.118539e+09           28.0000

In [25]:
doctors.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     str
 1   first_name        10 non-null     str
 2   last_name         10 non-null     str
 3   specialization    10 non-null     str
 4   phone_number      10 non-null     int64
 5   years_experience  10 non-null     int64
 6   hospital_branch   10 non-null     str
 7   email             10 non-null     str
dtypes: int64(2), str(6)
memory usage: 772.0 bytes

In [26]:
doctors.shape

(10, 8)

In [27]:
doctors.columns

Index(['doctor_id', 'first_name', 'last_name', 'specialization',
       'phone_number', 'years_experience', 'hospital_branch', 'email'],
      dtype='str')

In [28]:
treatments.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [29]:
treatments.tail()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
195,T196,A196,Chemotherapy,Advanced protocol,2477.80,2023-10-26
196,T197,A197,Physiotherapy,Standard procedure,975.49,2023-04-01
197,T198,A198,ECG,Basic screening,3383.72,2023-05-15
198,T199,A199,Chemotherapy,Basic screening,1472.17,2023-05-01
199,T200,A200,X-Ray,Basic screening,3288.15,2023-12-30

In [30]:
treatments.describe()

              cost
count   200.000000
mean   2756.249250
std    1298.125308
min     534.030000
25%    1563.412500
50%    2828.165000
75%    3836.627500
max    4973.630000

In [31]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    str
 1   appointment_id  200 non-null    str
 2   treatment_type  200 non-null    str
 3   description     200 non-null    str
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    str
dtypes: float64(1), str(5)
memory usage: 9.5 KB

In [32]:
treatments.shape

(200, 6)

In [33]:
treatments.columns

Index(['treatment_id', 'appointment_id', 'treatment_type', 'description',
       'cost', 'treatment_date'],
      dtype='str')

In [34]:
len(patients)

50

In [35]:
patients.isnull().sum()

patient_id            0
first_name            0
last_name             0
gender                0
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [36]:
len(appointments)

200

In [37]:
appointments.isnull().sum()

appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

In [38]:
len(billing)

200

In [41]:
#missing values
billing.isnull().sum()

bill_id           0
patient_id        0
treatment_id      0
bill_date         0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [40]:
len(doctors)

10

In [42]:
#missing values
doctors.isnull().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone_number        0
years_experience    0
hospital_branch     0
email               0
dtype: int64

In [43]:
len(treatments)

200

In [44]:
#missing values
treatments.isnull().sum()

treatment_id      0
appointment_id    0
treatment_type    0
description       0
cost              0
treatment_date    0
dtype: int64