In [1]:
#import library
import pandas as pd

In [3]:
#dataset load
data=pd.read_csv("car data.csv")

In [4]:
#first 5 rows
data.head()

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
0,1,lounge,51,882,25000,1,44.907242,8.611560,8900
1,2,pop,51,1186,32500,1,45.666359,12.241890,8800
2,3,sport,74,4658,142228,1,45.503300,11.417840,4200
3,4,lounge,51,2739,160000,1,40.633171,17.634609,6000
4,5,pop,73,3074,106880,1,41.903221,12.495650,5700

In [5]:
#last 5 rows
data.tail()

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
1515,1534,sport,51,3712,115280,1,45.069679,7.70492,5200
1516,1535,lounge,74,3835,112000,1,45.845692,8.66687,4600
1517,1536,pop,51,2223,60457,1,45.481541,9.41348,7500
1518,1537,lounge,51,2557,80750,1,45.000702,7.68227,5990
1519,1538,pop,51,1766,54276,1,40.323410,17.56827,7900

In [6]:
#dataset information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               1520 non-null   int64
 1   model            1520 non-null   str
 2   engine_power     1520 non-null   int64
 3   age_in_days      1520 non-null   int64
 4   km               1520 non-null   int64
 5   previous_owners  1520 non-null   int64
 6   lat              1520 non-null   float64
 7   lon              1520 non-null   float64
 8   price            1520 non-null   int64
dtypes: float64(2), int64(6), str(1)
memory usage: 107.0 KB

In [7]:
data.describe()

,ID,engine_power,age_in_days,km,previous_owners,lat,lon,price
count,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000,1520.000000
mean,768.854605,51.915132,1657.190789,53602.474342,1.123684,43.539485,11.571552,8564.311842
std,443.599478,4.010360,1290.870689,40181.202940,0.415901,2.137960,2.332344,1942.771619
min,1.000000,51.000000,366.000000,1232.000000,1.000000,36.855839,7.245400,2500.000000
25%,383.750000,51.000000,670.000000,20000.000000,1.000000,41.794763,9.505090,7100.000000
50%,769.500000,51.000000,1066.000000,39162.000000,1.000000,44.394096,11.869260,9000.000000
75%,1151.250000,51.000000,2623.750000,80000.000000,1.000000,45.467960,12.786127,10000.000000
max,1538.000000,77.000000,4658.000000,235000.000000,4.000000,46.795612,18.365520,11100.000000

In [8]:
#rows and columns count
data.shape

(1520, 9)

In [9]:
#columns names
data.columns

Index(['ID', 'model', 'engine_power', 'age_in_days', 'km', 'previous_owners',
       'lat', 'lon', 'price'],
      dtype='str')

In [52]:
#empty values count
data.isnull().sum()

ID                 0
model              0
engine_power       0
age_in_days        0
km                 0
previous_owners    0
lat                0
lon                0
price              0
dtype: int64

In [11]:
#unique values show
data['model'].unique()

<StringArray>
['lounge', 'pop', 'sport']
Length: 3, dtype: str

In [12]:
data['previous_owners'].unique()

array([1, 2, 3, 4])

In [13]:
#nunique()      (unique values count)
data['model'].nunique()

3

In [14]:
data['previous_owners'].nunique()

4

In [21]:
#sort_values     (descending)
data.sort_values(['price'],ascending=False)

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
667,676,lounge,51,487,17800,1,45.351528,10.844090,11100
485,492,pop,51,670,9000,1,44.988739,9.010500,11090
151,155,lounge,51,701,21580,1,41.125870,16.866659,11090
730,740,pop,51,1005,15000,2,41.903221,12.495650,11000
750,760,lounge,51,425,7778,1,41.903221,12.495650,11000
...,...,...,...,...,...,...,...,...,...
925,936,pop,73,4658,165000,2,45.584091,9.270960,3600
918,929,pop,51,4627,148000,1,45.356602,9.203450,3500
265,269,lounge,51,4383,135762,1,43.879860,10.782810,3390
1316,1331,lounge,51,4627,171150,1,45.830688,12.033340,2900
950,961,pop,51,4414,201000,1,45.141140,9.108080,2500

In [22]:
#sort_values     (ascending)
data.sort_values(['price'])

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
950,961,pop,51,4414,201000,1,45.141140,9.108080,2500
1316,1331,lounge,51,4627,171150,1,45.830688,12.033340,2900
265,269,lounge,51,4383,135762,1,43.879860,10.782810,3390
918,929,pop,51,4627,148000,1,45.356602,9.203450,3500
925,936,pop,73,4658,165000,2,45.584091,9.270960,3600
...,...,...,...,...,...,...,...,...,...
470,477,lounge,51,425,18276,1,38.318069,16.394899,11000
116,119,lounge,51,425,16518,1,44.399971,8.274500,11000
485,492,pop,51,670,9000,1,44.988739,9.010500,11090
151,155,lounge,51,701,21580,1,41.125870,16.866659,11090
667,676,lounge,51,487,17800,1,45.351528,10.844090,11100

In [23]:
#filtering
data[data['price']<=10000]

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
0,1,lounge,51,882,25000,1,44.907242,8.611560,8900
1,2,pop,51,1186,32500,1,45.666359,12.241890,8800
2,3,sport,74,4658,142228,1,45.503300,11.417840,4200
3,4,lounge,51,2739,160000,1,40.633171,17.634609,6000
4,5,pop,73,3074,106880,1,41.903221,12.495650,5700
...,...,...,...,...,...,...,...,...,...
1515,1534,sport,51,3712,115280,1,45.069679,7.704920,5200
1516,1535,lounge,74,3835,112000,1,45.845692,8.666870,4600
1517,1536,pop,51,2223,60457,1,45.481541,9.413480,7500
1518,1537,lounge,51,2557,80750,1,45.000702,7.682270,5990
1519,1538,pop,51,1766,54276,1,40.323410,17.568270,7900

In [24]:
data[data['previous_owners']<=1]

,ID,model,engine_power,age_in_days,km,previous_owners,lat,lon,price
0,1,lounge,51,882,25000,1,44.907242,8.611560,8900
1,2,pop,51,1186,32500,1,45.666359,12.241890,8800
2,3,sport,74,4658,142228,1,45.503300,11.417840,4200
3,4,lounge,51,2739,160000,1,40.633171,17.634609,6000
4,5,pop,73,3074,106880,1,41.903221,12.495650,5700
...,...,...,...,...,...,...,...,...,...
1515,1534,sport,51,3712,115280,1,45.069679,7.704920,5200
1516,1535,lounge,74,3835,112000,1,45.845692,8.666870,4600
1517,1536,pop,51,2223,60457,1,45.481541,9.413480,7500
1518,1537,lounge,51,2557,80750,1,45.000702,7.682270,5990
1519,1538,pop,51,1766,54276,1,40.323410,17.568270,7900

In [33]:
#groupby     (model wise price count)
data.groupby('model')['price'].count()

model
lounge    1079
pop        356
sport       85
Name: price, dtype: int64

In [35]:
data.groupby('previous_owners')['model'].count()

previous_owners
1    1372
2     117
3      22
4       9
Name: model, dtype: int64

In [36]:
#loc[]   (using columns names to find the data)    (position,columns name)
data.loc[2,'model']

'sport'

In [37]:
data.loc[4,'km']

np.int64(106880)

In [38]:
#iloc[]    (using index value to find the data)
data.iloc[2,1]

'sport'

In [39]:
#rename()     (rename column name )
data1=data.rename(columns={'model':'model_name'})
data1

,ID,model_name,engine_power,age_in_days,km,previous_owners,lat,lon,price
0,1,lounge,51,882,25000,1,44.907242,8.611560,8900
1,2,pop,51,1186,32500,1,45.666359,12.241890,8800
2,3,sport,74,4658,142228,1,45.503300,11.417840,4200
3,4,lounge,51,2739,160000,1,40.633171,17.634609,6000
4,5,pop,73,3074,106880,1,41.903221,12.495650,5700
...,...,...,...,...,...,...,...,...,...
1515,1534,sport,51,3712,115280,1,45.069679,7.704920,5200
1516,1535,lounge,74,3835,112000,1,45.845692,8.666870,4600
1517,1536,pop,51,2223,60457,1,45.481541,9.413480,7500
1518,1537,lounge,51,2557,80750,1,45.000702,7.682270,5990
1519,1538,pop,51,1766,54276,1,40.323410,17.568270,7900

In [48]:
#drop()          (remove columns)
data2=data1.drop(['lon','lat','ID','age_in_days'],axis=1)
data2

     model_name  engine_power      km  previous_owners  price
0        lounge            51   25000                1   8900
1           pop            51   32500                1   8800
2         sport            74  142228                1   4200
3        lounge            51  160000                1   6000
4           pop            73  106880                1   5700
...         ...           ...     ...              ...    ...
1515      sport            51  115280                1   5200
1516     lounge            74  112000                1   4600
1517        pop            51   60457                1   7500
1518     lounge            51   80750                1   5990
1519        pop            51   54276                1   7900

[1520 rows x 5 columns]

In [49]:
#drop_duplicates()     ( to check duplicates)     (false means no duplicate,true means duplicate) 
data2.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1515    False
1516    False
1517    False
1518    False
1519    False
Length: 1520, dtype: bool

In [50]:
#new CSV file
data2.to_csv("Car data_cleaned.csv",index=False)

In [51]:
data2

     model_name  engine_power      km  previous_owners  price
0        lounge            51   25000                1   8900
1           pop            51   32500                1   8800
2         sport            74  142228                1   4200
3        lounge            51  160000                1   6000
4           pop            73  106880                1   5700
...         ...           ...     ...              ...    ...
1515      sport            51  115280                1   5200
1516     lounge            74  112000                1   4600
1517        pop            51   60457                1   7500
1518     lounge            51   80750                1   5990
1519        pop            51   54276                1   7900

[1520 rows x 5 columns]