In [1]:
#import library
import pandas as pd

In [2]:
#dataset load
data=pd.read_csv("movies.csv")

In [3]:
#first 5 rows
data.head()

   srno                 movie  year  rating    time
0     1  The Nightmare Before  1993     3.9  4568.0
1     2             The Mummy  1932     3.5  4388.0
2     3  Orphans of the Storm  1921     3.2  9062.0
3     4  The Object of Beauty  1991     2.8  6150.0
4     5            Night Tide  1963     2.8  5126.0

In [4]:
#last 5 rows
data.tail()

,srno,movie,year,rating,time
49585,49586,Winter Wonderland,2013,2.8,1812.0
49586,49587,Top Gear: Series 19: Africa Special,2013,NaN,6822.0
49587,49588,Fireplace For Your Home: Crackling Fireplace w...,2010,NaN,3610.0
49588,49589,Kate Plus Ei8ht,2010,2.7,NaN
49589,49590,Kate Plus Ei8ht: Season 1,2010,2.7,NaN

In [5]:
#dataset information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 49590 entries, 0 to 49589
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   srno    49590 non-null  int64
 1   movie   49590 non-null  str
 2   year    49590 non-null  int64
 3   rating  10814 non-null  float64
 4   time    45836 non-null  float64
dtypes: float64(2), int64(2), str(1)
memory usage: 1.9 MB

In [6]:
data.describe()

               srno          year        rating          time
count  49590.000000  49590.000000  10814.000000  45836.000000
mean   24795.500000   2002.303428      3.451248   2628.445436
std    14315.544261     12.534555      0.495601   1604.646265
min        1.000000   1913.000000      1.400000     52.000000
25%    12398.250000   1999.000000      3.100000   1356.000000
50%    24795.500000   2007.000000      3.500000   2563.000000
75%    37192.750000   2010.000000      3.800000   2877.000000
max    49590.000000   2014.000000      4.500000  28813.000000

In [7]:
#rows and columns count
data.shape

(49590, 5)

In [8]:
#columns names
data.columns

Index(['srno', 'movie', 'year', 'rating', 'time'], dtype='str')

In [9]:
#empty values count
data.isnull().sum()

srno          0
movie         0
year          0
rating    38776
time       3754
dtype: int64

In [10]:
#empty rows remove
data1=data.dropna()

In [11]:
#empty values fill
data1=data1.fillna(0)

In [12]:
#empty values count in data1
data1.isnull().sum()

srno      0
movie     0
year      0
rating    0
time      0
dtype: int64

In [13]:
#values counts
data1['year'].value_counts()

year
2011    827
2012    769
2010    666
2009    485
2007    342
       ...
1922      2
1915      1
1916      1
1918      1
2014      1
Name: count, Length: 101, dtype: int64

In [14]:
data1['rating'].value_counts()

rating
3.6    588
3.4    563
3.5    562
3.3    544
3.7    543
3.2    518
3.1    501
3.0    447
3.8    413
2.9    356
3.9    342
2.8    305
2.7    230
4.0    204
2.6    157
2.5    152
4.1    117
2.4    109
2.3     99
2.1     72
4.2     71
2.2     53
1.9     25
4.3     22
2.0     22
1.8     18
1.7     10
4.4      9
4.5      4
1.6      4
Name: count, dtype: int64

In [15]:
#unique
data1['year'].unique()

array([1993, 1932, 1921, 1991, 1963, 1985, 1994, 1929, 1995, 1919, 1996,
       1915, 1978, 1971, 1935, 1981, 1989, 1987, 1986, 1972, 1992, 1938,
       1990, 1999, 1976, 1973, 1979, 1975, 1920, 1982, 1950, 1970, 1968,
       1939, 1988, 1974, 1980, 1959, 1956, 1952, 1923, 1969, 1964, 1947,
       1984, 1925, 1936, 1997, 1998, 1927, 1983, 1924, 1928, 1937, 1977,
       1953, 1916, 1960, 1926, 1941, 1949, 1931, 1955, 1940, 2000, 1962,
       1966, 2001, 1942, 1967, 1954, 1914, 1958, 1951, 1945, 1965, 1944,
       1934, 1933, 1948, 1957, 2002, 2003, 2004, 1946, 1961, 2005, 1922,
       1930, 2010, 2011, 1943, 2006, 2007, 2008, 2009, 2013, 2012, 1913,
       1918, 2014])

In [16]:
data1['rating'].unique()

array([3.9, 3.5, 3.2, 2.8, 3.8, 3.4, 3.3, 3.6, 2.9, 4. , 3.7, 3.1, 3. ,
       2.5, 2.7, 4.1, 2.6, 2.4, 2.2, 4.2, 2.1, 4.3, 1.9, 2.3, 2. , 1.8,
       4.4, 4.5, 1.7, 1.6])

In [17]:
# nunique()     (unique values count)
data1['year'].nunique()

101

In [18]:
data1['rating'].nunique()

30

In [19]:
#sort_values(descending order)
data1.sort_values('year',ascending=False)

,srno,movie,year,rating,time
49560,49561,The Square (Trailer),2014,3.6,154.0
49554,49555,Saving Santa,2013,3.8,5038.0
49552,49553,El Fuente: 24 MP,2013,3.5,484.0
49515,49516,Stalled,2013,2.6,5089.0
49578,49579,Transformers Prime Beast Hunters: Predacons Ri...,2013,4.2,3950.0
...,...,...,...,...,...
42671,42672,Fantômas IV: Fantômas vs. Fantômas,1914,2.5,3590.0
42672,42673,Fantômas V: The False Magistrate,1914,2.4,4247.0
14327,14328,Fantômas III: The Murderous Corpse,1913,2.6,5432.0
42664,42665,Fantômas I: In the Shadow of the Guillotine,1913,2.9,3268.0
42670,42671,Fantômas II: Juve vs. Fantômas,1913,2.7,3718.0

In [20]:
#sort_values   (ascending )
data1.sort_values('rating')

        srno                               movie  year  rating    time
44595  44596                  Where Is Parsifal?  1984     1.6  4937.0
35597  35598                  1313: UFO Invasion  2011     1.6  5053.0
44656  44657                    Makers Our Story  2011     1.6  8162.0
37613  37614              1313: Hercules Unbound  2012     1.6  4339.0
44639  44640                                Maya  1982     1.7  6778.0
...      ...                                 ...   ...     ...     ...
8019    8020  Gifted Hands: The Ben Carson Story  2009     4.4  5411.0
30425  30426                        The Avengers  2012     4.5  8575.0
49503  49504      Lilyhammer: Season 2 (Trailer)  2013     4.5   106.0
44097  44098      Arrested Development (Trailer)  2013     4.5    97.0
43443  43444                           Blackfish  2013     4.5  4985.0

[7060 rows x 5 columns]

In [21]:
#filtering
data1[data1['rating']>=4.5]

        srno                           movie  year  rating    time
30425  30426                    The Avengers  2012     4.5  8575.0
43443  43444                       Blackfish  2013     4.5  4985.0
44097  44098  Arrested Development (Trailer)  2013     4.5    97.0
49503  49504  Lilyhammer: Season 2 (Trailer)  2013     4.5   106.0

In [22]:
data1[data1['year']>=2014]

        srno                 movie  year  rating   time
49560  49561  The Square (Trailer)  2014     3.6  154.0

In [23]:
data1[data1['rating']<=3]

        srno                     movie  year  rating     time
3          4      The Object of Beauty  1991     2.8   6150.0
4          5                Night Tide  1963     2.8   5126.0
12        13     The Birth of a Nation  1915     2.9  12118.0
14        15            Big Doll House  1971     2.9   5696.0
42        43                Easy Money  1987     2.8   5794.0
...      ...                       ...   ...     ...      ...
49572  49573        El Fuente: 50 MP10  2013     2.9    464.0
49573  49574        El Fuente: 30 MP10  2013     2.8    470.0
49581  49582  Mumfie's White Christmas  1996     2.4   1350.0
49583  49584              Sunset Strip  2012     3.0   5770.0
49585  49586         Winter Wonderland  2013     2.8   1812.0

[2059 rows x 5 columns]

In [24]:
#groupby() year wise movies count
data1.groupby('year')['movie'].count()

year
1913      3
1914      3
1915      1
1916      1
1918      1
       ...
2010    666
2011    827
2012    769
2013    265
2014      1
Name: movie, Length: 101, dtype: int64

In [25]:
#loc[] (column name/label  to use find the data)
data1.loc[1,'movie']

'The Mummy'

In [26]:
data1.loc[16,'year']

np.int64(1935)

In [27]:
#iloc[](using index number to find the data)
data1.iloc[1,1]

'The Mummy'

In [28]:
data1.iloc[16,2]

np.int64(1935)

In [29]:
#rename()  (column name to change)
data2=data1.rename(columns={'movie':'movie_name'})
data2

,srno,movie_name,year,rating,time
0,1,The Nightmare Before,1993,3.9,4568.0
1,2,The Mummy,1932,3.5,4388.0
2,3,Orphans of the Storm,1921,3.2,9062.0
3,4,The Object of Beauty,1991,2.8,6150.0
4,5,Night Tide,1963,2.8,5126.0
...,...,...,...,...,...
49581,49582,Mumfie's White Christmas,1996,2.4,1350.0
49582,49583,Lady Gaga &#38; The Muppets' Holiday Spectacular,2013,3.1,3496.0
49583,49584,Sunset Strip,2012,3.0,5770.0
49584,49585,Silver Bells,2013,3.5,5287.0
49585,49586,Winter Wonderland,2013,2.8,1812.0

In [30]:
#drop()  (remove column)
data3=data2.drop('time',axis=1)
data3

        srno                                        movie_name  year  rating
0          1                              The Nightmare Before  1993     3.9
1          2                                         The Mummy  1932     3.5
2          3                              Orphans of the Storm  1921     3.2
3          4                              The Object of Beauty  1991     2.8
4          5                                        Night Tide  1963     2.8
...      ...                                               ...   ...     ...
49581  49582                          Mumfie's White Christmas  1996     2.4
49582  49583  Lady Gaga &#38; The Muppets' Holiday Spectacular  2013     3.1
49583  49584                                      Sunset Strip  2012     3.0
49584  49585                                      Silver Bells  2013     3.5
49585  49586                                 Winter Wonderland  2013     2.8

[7060 rows x 4 columns]

In [31]:
#duplicated()        (false=no duplicates,true =duplicates have)
data3.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49581    False
49582    False
49583    False
49584    False
49585    False
Length: 7060, dtype: bool

In [33]:
#new csv file
data3.to_csv("movies_cleaned.csv",index=1)
data3

        srno                                        movie_name  year  rating
0          1                              The Nightmare Before  1993     3.9
1          2                                         The Mummy  1932     3.5
2          3                              Orphans of the Storm  1921     3.2
3          4                              The Object of Beauty  1991     2.8
4          5                                        Night Tide  1963     2.8
...      ...                                               ...   ...     ...
49581  49582                          Mumfie's White Christmas  1996     2.4
49582  49583  Lady Gaga &#38; The Muppets' Holiday Spectacular  2013     3.1
49583  49584                                      Sunset Strip  2012     3.0
49584  49585                                      Silver Bells  2013     3.5
49585  49586                                 Winter Wonderland  2013     2.8

[7060 rows x 4 columns]