In [1]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#load dataset
data=pd.read_csv("Student marks dataset.csv")

In [6]:
#first 5 rows
data.head()

  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65

In [7]:
#last 5 rows
data.tail()

  student  language  science  maths  history
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0    NaN       34
6  carrol        50     90.0   45.0       23

In [8]:
#dataset  information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   student   7 non-null      str
 1   language  7 non-null      int64
 2   science   5 non-null      float64
 3   maths     6 non-null      float64
 4   history   7 non-null      int64
dtypes: float64(2), int64(2), str(1)
memory usage: 412.0 bytes

In [9]:
data.describe()

        language    science  maths    history
count   7.000000   5.000000    6.0   7.000000
mean   54.285714  54.000000   43.0  42.857143
std    35.523299  24.217762   26.0  17.062909
min    10.000000  23.000000   12.0  23.000000
25%    25.000000  45.000000   32.5  33.000000
50%    50.000000  56.000000   39.5  34.000000
75%    90.000000  56.000000   45.0  55.000000
max    90.000000  90.000000   90.0  67.000000

In [10]:
#rows and columns count
data.shape

(7, 5)

In [12]:
#columns names
data.columns

Index(['student', 'language', 'science', 'maths', 'history'], dtype='str')

In [13]:
#empty values count
data.isnull().sum()

student     0
language    0
science     2
maths       1
history     0
dtype: int64

In [22]:
#fillna()        (fill values in empty row)
data1=data1.fillna(0)

In [23]:
#empty values count in data1
data1.isnull().sum()

student     0
language    0
science     0
maths       0
history     0
dtype: int64

In [27]:
data1.head()

  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
2   sammy        90     23.0   12.0       32
4   peter        30     56.0   45.0       65
6  carrol        50     90.0   45.0       23

In [28]:
data1.shape

(4, 5)

In [32]:
#to use numpy
#average of language
np.mean(data1['language'])

np.float64(65.0)

In [33]:
np.mean(data1['science'])

np.float64(56.25)

In [34]:
np.mean(data1['maths'])

np.float64(34.0)

In [35]:
np.mean(data1['history'])

np.float64(38.5)

In [42]:
#max    (highest value)
np.max(data1['maths'])

np.float64(45.0)

In [43]:
#min        (lowest value)
np.min(data1['maths'])

np.float64(12.0)

In [44]:
#sum   (total language  marks)
np.sum(data1['maths'])

np.float64(136.0)

In [41]:
#median
np.median(data1['maths'])

np.float64(39.5)

In [45]:
#sort
np.sort(data1['maths'])

array([12., 34., 45., 45.])

In [47]:
#unique
np.unique(data1['maths'])

array([12., 34., 45.])